#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
## ############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Add default JVM options here. You can also use a Java runtime available.
DEFAULT_JVM_OPTS=""

# Determine the current working directory
if [ -n "$JAVA_HOME" ]; then
  JAVA_EXE="$JAVA_HOME/bin/java"
else
  JAVA_EXE="java"
fi

# Fail if JAVA_HOME is set and not valid
if [ -n "$JAVA_HOME" ] && [ ! -x "$JAVA_EXE" ]; then
  echo "ERROR: JAVA_HOME is set to an invalid path: $JAVA_HOME"
  exit 1
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
APP_HOME=$(cd "$(dirname "$0")" && pwd)
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Escape application args
save () {
    for i in "$@"
    do
        printf '%s\n' "$i" | sed "s/'/'\\\\''/g"
    done
}

# Collect all arguments
for arg in "$@"
  do
    case "$arg" in
        -classpath|-cp)
        CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
        ;;
    esac
done

# Check the jar file exists
if [ ! -f "$CLASSPATH" ]; then
    echo "ERROR: Could not find Gradle wrapper JAR at $CLASSPATH"
    exit 1
fi

# Execute Gradle
exec "$JAVA_EXE" $DEFAULT_JVM_OPTS "$@" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
